//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpellMaster {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpellMaster.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indentifiers should be spelled correctly.
        /// </summary>
        internal static string AnalyzerDescription {
            get {
                return ResourceManager.GetString("AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier &apos;{0}&apos; contains a misspelling.
        /// </summary>
        internal static string AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier contains a misspelling.
        /// </summary>
        internal static string AnalyzerTitle {
            get {
                return ResourceManager.GetString("AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] en_US_aff {
            get {
                object obj = ResourceManager.GetObject("en_US_aff", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 52890
        ///A/1	1
        ///AA/2	1
        ///AAA
        ///Aachen
        ///aah	1
        ///Aaliyah/3
        ///aardvark/1	1
        ///Aaron
        ///ab
        ///AB/2	1
        ///ABA
        ///aback	1
        ///abacus/4	1
        ///abaft	1
        ///abalone/1	1
        ///abandon/5	1
        ///abandoned	1
        ///abandonment/2	1
        ///abase/6	1
        ///abasement/2	1
        ///abash/7	1
        ///abashed/8	1
        ///abashment/2	1
        ///abate/6	1
        ///abatement/2	1
        ///abates	2
        ///abattoir/1	1
        ///Abbas
        ///Abbasid	1
        ///abbe/1	1
        ///abbes/9	1
        ///abbess/4	1
        ///abbey/1	1
        ///abbot/1	1
        ///Abbott/3
        ///abbr
        ///abbrev/10	1
        ///abbreviate/6	1
        ///abbreviation/1	1
        ///Abby/3
        ///ABC/1	1
        ///abdicate/6	1
        ///abdication/1	1
        ///abdomen/1	1
        ///abdominal	1
        ///abduct/11	1
        ///abduction/1	1
        ///abductor/1	1
        ///Abdul/3
        ///Abe/3
        ///abea [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string en_US_dic {
            get {
                return ResourceManager.GetString("en_US_dic", resourceCulture);
            }
        }
    }
}
